[theme]
base = "dark"
primaryColor = "#5c6bc0"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#161b27"
textColor = "#fafafa"
font = "sans serif"

[server]
headless = false
port = 8501

[browser]
gatherUsageStats = false
