[theme]
base = "light"
primaryColor = "#1d6cf2"
backgroundColor = "#eaeef6"
secondaryBackgroundColor = "#ffffff"
textColor = "#0a1f44"
font = "sans serif"

[server]
headless = false
port = 8501
runOnSave = true

[browser]
gatherUsageStats = false
